version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: acta_postgres
    environment:
      POSTGRES_USER: acta_user
      POSTGRES_PASSWORD: acta_password
      POSTGRES_DB: acta_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U acta_user -d acta_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - acta_network

volumes:
  postgres_data:

networks:
  acta_network:
    driver: bridge 